- hosts: data4
  roles:
    - role: ansible-elasticsearch
  vars:
    es_instance_name: "node1"
    es_config:
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      cluster.name: "test-cluster"
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_port: 9200
    es_plugins: {}
    
- hosts: data4
  roles:
    - role: ansible-elasticsearch
  vars:
    es_instance_name: "node2"
    es_api_port: 9201
    es_config:
      http.port: 9201
      transport.tcp.port: 9301
      node.data: true
      node.master: false
      cluster.name: "test-cluster"
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins: {}
