--- 
- hosts: data4
  handlers:
  - name: disable shard allocation
    listen: stop elasticsearch
    uri:
     url: http://{{ es_api_host }}:{{ es_api_port }}/_cluster/settings
     method: PUT
     body_format: json
     body: "{\"persistent\":{\"cluster.routing.allocation.enable\":\"none\"}}"
    register: result
    until: result.json.acknowledged == true
    retries: 5
    delay: 3
    changed_when: result.json.acknowledged == true

  - name: stop es
    listen: stop elasticsearch
    service:
     name: elasticsearch
     state: stopped
  
  - name: wait es stopped
    listen: stop elasticsearch
    wait_for: host={{ es_api_host }} port={{ es_api_port }} delay=5 state=absent
    changed_when: true
    notify:
     - start elasticsearch

  - name: start es
    listen: start elasticsearch
    service:
     name: elasticsearch
     state: started

  - name: wait es started
    listen: start elasticsearch
    wait_for: host={{ es_api_host }} port={{ es_api_port }} delay=5 state=present
    changed_when: true

  - name: wait for cluster
    listen: start elasticsearch
    uri:
     url: http://{{ es_api_host }}:{{ es_api_port }}/_cat/nodes
     method: GET
     return_content: yes
    register: get_result
    until: get_result.content.find(es_api_host) != -1
    retries: 30
    delay: 3
    notify: test

  - name: enable shard allocation
    listen: start elasticsearch
    uri:
     url: http://{{ es_api_host }}:{{ es_api_port }}/_cluster/settings
     method: PUT
     body_format: json
     body: "{\"persistent\":{\"cluster.routing.allocation.enable\":null}}"
    register: result
    until: result.json.acknowledged == true
    retries: 5
    delay: 3
    changed_when: result.json.acknowledged == true

  tasks:
  - name: Check Elasticsearch in Update
    command: "apt-get -u upgrade --assume-no"
    register: aptupdate
    failed_when: "'FAILED' in aptupdate.stderr"
    #changed_when: "'elasticsearch' in aptupdate.stdout"
    notify:
     - stop elasticsearch
     #- Start ES
   
### wait for cluster joined und start if stopped implementieren
